### ISSUE TITLE
Question: how to express call to default method of interface

### ISSUE THREAD

**Issue by borkdude** [jgpc42/insn#11]
Given the following example:

``` clojure
(ns user)

(require '[insn.core :as insn])

(def class-data
  {:name 'my.pkg.Iterator
   :version 1.8
   :interfaces ['java.util.Iterator]
   :fields [{:flags #{:public :static}, :name "VALUE", :type :boolean, :value true}]
   :methods [{:flags #{:public}, :name "hasNext"
              :desc [:boolean]
              :emit [[:getstatic :this "VALUE" :boolean]
                     [:ireturn]]}
             {:flags #{:public}, :name "remove"
              :emit [[:aload 0]
                     [:invokespecial java.util.Iterator :remove [:void]]
                     [:return]]}]})

(def result (insn/visit class-data))

(def class-object (insn/define class-data))

(-> class-object .newInstance (.hasNext))
```

The last expression returns `true`. But when I call the `remove` method, which is supposed to call the default method of the interface, I get:

``` clojure
(-> class-object .newInstance (.remove))
```

```
1. Unhandled java.lang.IncompatibleClassChangeError
   Method 'void java.util.Iterator.remove()' must be InterfaceMethodref constant
```

In Java this would be:

``` java
  java.util.Iterator.super.remove();
```

How can I write this?

**Comment by borkdude** [comment]
I kind of figured it out. I need the overload and pass the boolean `itf true`:

``` clojure
(.visitMethodInsn v &op (util/class-desc cls)
                         mname (util/method-desc desc) true)
```

but this is currently not supported by insn. Could this be added?

**Comment by borkdude** [comment]
Btw, if you're open to adding this option, I could try a PR myself. It would be a nice opportunity to learn more about this library.

**Comment by jgpc42** [comment]
Sorry for the late reply; I was away from the computer this weekend.

Thanks for bringing this deficiency to my attention. As you noted, this should be a trivial change and I'd be happy to add support for this.

Unless you'd rather send a PR, I'll include this feature along with upgrading the project to test against Clojure 1.11, which I've had on my todo list. I should have this done in the next day or two.

Thanks again.

**Comment by borkdude** [comment]
Oh, please go ahead :)

**Comment by jgpc42** [comment]
I just pushed version [0.5.3](https://clojars.org/insn) which includes [support](https://jgpc42.github.io/insn/doc/insn.op.html#var-invokespecial) for the interface flag. [Here's a test case](https://github.com/jgpc42/insn/blob/d95a583/test/insn/v8_bytecode_test.clj) adapted from this issue.

Let me know if you have any more issues. Thanks.

**Comment by borkdude** [comment]
Thanks a lot!
