### ISSUE TITLE
I love this library

### ISSUE THREAD

**Issue by cnuernber** [jgpc42/insn#4]
Just wanted to say so publicly and officially.

We use it at a pretty deep level to build optimized dimension-specific indexing systems for ND operations:

https://github.com/techascent/tech.datatype/blob/57988eef8e544b02f6f36a1b6f52aef3a02cb0d1/src/tech/v2/tensor/dimensions/global_to_local.clj

I wrote a sort of blog post about my experience using it a while ago and meant to post it here:

https://github.com/techascent/tech.datatype/blob/57988eef8e544b02f6f36a1b6f52aef3a02cb0d1/docs/dimensions-bytecode-gen.md

**Comment by jgpc42** [comment]
Thank you very much for your kind words.

I really enjoyed your blog post. Your project looks like exactly the kind of thing this library was designed for.

Do you mind if I add your project to the "Projects using insn" section of the [README](https://github.com/jgpc42/insn#projects-using-insn)? You can give me a short description to use, if you would like. I'd also add a link to your blog post on the "Higher Level API" [wiki page](https://github.com/jgpc42/insn/wiki/Higher-Level-API), if I have your permission.

Thanks again!

**Comment by cnuernber** [comment]
Please, by all means, anything you like. 

Working on next version of datatype library btw, which will (among other things) combine everything above with graal native.

**Comment by jgpc42** [comment]
Thank you. I've added the links. I'll be watching for the next version!

**Comment by cnuernber** [comment]
Slack announcement: https://clojurians.slack.com/archives/C06MAR553/p1614700654191700

I used insn to dynamically generate bindings for the different ffi systems in order to implement a [data driven, multi backend ffi pathway](https://cnuernber.github.io/dtype-next/tech.v3.datatype.ffi.html).  

Having this done with insn means I am not limited by Clojure's typesystem which, for instance, is unable to use [invokeExact on a method handle](https://docs.oracle.com/javase/7/docs/api/java/lang/invoke/MethodHandle.html#invokeExact(java.lang.Object...)).

It means I can also, in code, generate a class suitable for jna's directmapping pathway and of course generating and loading the classes is pretty much instant as there really isn't a compilation process.

Just FYI :-).  This is great :-).
