### ISSUE TITLE
How to use labels?

### ISSUE THREAD

**Issue by cnuernber** [jgpc42/insn#5]
Hey, still really enjoying this library!

I am working on JDK16 support for [dtype-next](https://github.com/cnuernber/dtype-next/).

I am curious how to use the goto/if statements; specifically `if-icmpne`.  How do I label a section of code?

**Comment by jgpc42** [comment]
Hello again! Glad to hear it.

Regions of bytecode are denoted with the `:mark` op. By default, insn [auto-generates](https://github.com/jgpc42/insn/blob/2cc51ee/src/insn/util.clj#L185) labels (ASM `Label` objects) based on arbitrary values and caches them for each emitted method. I usually use [keywords](https://github.com/jgpc42/insn/wiki/Faster-HashCode).

As mentioned in the README, take a look at the wiki, or the [tests](https://github.com/jgpc42/insn/blob/cf46849/test/insn/core_test.clj#L154) for additional examples.

Thanks.

**Comment by cnuernber** [comment]
Thanks, this will do!
