### ISSUE TITLE
static initializer section

### ISSUE THREAD

**Issue by cnuernber** [jgpc42/insn#8]
I may have missed it but how would you recommend I code up a static initialization section?

**Comment by jgpc42** [comment]
[From the docs](https://jgpc42.github.io/insn/doc/insn.core.html#var-visit):

```
Class/interface methods, constructors, and static initializers are
provided as maps.

:name   method name (required). Can be either :init or :clinit,
        designating a constructor or the static initializer,
        respectively.
...
```

[Here's a test demonstrating `:clinit`](https://github.com/jgpc42/insn/blob/cf46849/test/insn/core_test.clj#L45).

Please see the documentation, wiki, and/or the tests for usage information and examples. Thanks.

**Comment by cnuernber** [comment]
Perfect, thanks!
